zhengzihui/fr_app/urls.py
#-*- coding:utf-8 -*-

from django.conf.urls import include, url
import fr_app.views

urlpatterns = [
    #free require part（免费需求发布）
    url(r'^frame/',fr_app.views.frame,name='frame'),
    url(r'^verification/',fr_app.views.verification,name='verification'),
    url(r'^require_finish',fr_app.views.require_finish,name='require_finish'),
    #Supporting Center part (配套中心)（懒得再做一个独立的app了，所以就放到这里）
    url(r'^supporting_center/frame',fr_app.views.supporting_center_frame
        ,name='supporting_center_frame'),
    url(r'^supporting_center/iteminfo',fr_app.views.supporting_center_iteminfo
        ,name='supporting_center_iteminfo'),
    url(r'^supporting_center/filter_labels',fr_app.views.supporting_center_filter_labels
        ,name='supporting_center_filter_labels'),
    url(r'^supporting_center/shoucang_item/',fr_app.views.supporting_center_shoucang_item
        ,name="supporting_center_shoucang_item"),
    url(r'^supporting_center/sc_search_result_load/',fr_app.views.sc_search_result_load),
]

zhengzihui/zhengzihui/urls.py
#coding:utf-8
"""zhengzihui URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.8/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Add an import:  from blog import urls as blog_urls
    2. Add a URL to urlpatterns:  url(r'^blog/', include(blog_urls))
"""
from django.conf.urls import include, url
from django.contrib import admin
import zhengzihui_app.views
#from yz_urls import *
urlpatterns = [
    url(r'^item_sortbyLevel',zhengzihui_app.views.item_sortbyLevel,name='item_sortbyLevel'),url(r'^admin/', include(admin.site.urls)),
    url(r'^free_require/', include('fr_app.urls')),
    url(r'^index/$',zhengzihui_app.views.index,name='index'),
    url(r'^hire/$',zhengzihui_app.views.newhire,name='newhire'),
    url(r'^search/$',zhengzihui_app.views.Searchgoods,name='Searchgoods'),
    
    url(r'^payok/$',zhengzihui_app.views.Payback,name='payok'),
    #zss 二级页面

    url(r'^search_result/$',zhengzihui_app.views.search_result,name='search_result'),

    
    
    
    url(r'^search_result_load/$',zhengzihui_app.views.search_result_load,name='search_result_load'),#用来干嘛的？？
    url(r'^filter_labels/$',zhengzihui_app.views.filter_labels,name='filter_labels'),#当用户选择了筛选条件之后，将值传到主页，再次跳到主页



    url(r'^searchforc/', zhengzihui_app.views.tag_autocomplete,name='auto'),
    

#用户中心
    url(r'^zzh/user_center/', zhengzihui_app.views.user_center,name="user_center"),
    
    #用户信息
        #我的信息
    url(r'^zzh/my_info/', zhengzihui_app.views.my_info,name="my_info"),
    #总览
    #url(r'^zzh/view_all/', "zhengzihui_app.views.view_all",name="view_all"),
        #保存修改信息
    url(r'^zzh/modify_user/', zhengzihui_app.views.modify_user,name="modify_user"),
        #安全中心
    url(r'^zzh/safe_center/', zhengzihui_app.views.safe_center,name="safe_center"),
        #支付绑定
    url(r'^zzh/pay_combine/', zhengzihui_app.views.pay_combine,name="pay_combine"),
        #等级与成长
    url(r'^zzh/grade_grow/', zhengzihui_app.views.grade_grow,name="grade_grow"),

#商家中心
    url(r'^zzh/merchant_center/', zhengzihui_app.views.merchant_center,name="merchant_center"),    
    #商家保存修改信息
    url(r'^zzh/modify_merchant/', zhengzihui_app.views.modify_merchant,name="modify_merchant"),    

    #订单管理
        #全部订单
    url(r'^zzh/all_orders/', zhengzihui_app.views.all_orders,name="all_orders"),
    url(r'^zzh/all_orders_back/', zhengzihui_app.views.all_orders_back,name="all_orders_back"),
    #未支付
    url(r'^zzh/not_pay/', zhengzihui_app.views.not_pay,name="not_pay"),
        #已支付
    url(r'^zzh/payed/', zhengzihui_app.views.payed,name="payed"),
       #已发货
    url(r'^zzh/delivered/', zhengzihui_app.views.delivered,name="delivered"),
       #已验收
    url(r'^zzh/checked/', zhengzihui_app.views.checked,name="checked"),
       #已取消
    url(r'^zzh/delete/', zhengzihui_app.views.delete,name="delete"),

       #订单详情
    url(r'^zzh/order_detail/', zhengzihui_app.views.order_detail,name="order_detail"),        
    
       #确认订单
    url(r'^order_enter/', zhengzihui_app.views.order_enter,name="order_enter"),
       #取消订单
    url(r'^order_giveup/', zhengzihui_app.views.order_giveup,name="order_giveup"),
       #删除订单
    url(r'^order_delete/', zhengzihui_app.views.order_delete,name="order_delete"),
       #点击评论按钮
    url(r'^order_commit/', zhengzihui_app.views.order_commit,name="order_commit"),
       #添加评论
    url(r'^order_add_commit/', zhengzihui_app.views.order_add_commit,name="order_add_commit"),
	
	

		
		
    #评价管理
        #我的评价
    url(r'^zzh/my_evaluate/', zhengzihui_app.views.my_evaluate,name="my_evaluate"),
        #评价统计
    url(r'^zzh/statistics/', zhengzihui_app.views.statistics,name="statistics"),
    
    
    #主页底部链接页面部分 友情链接
    url(r'^friend_link',zhengzihui_app.views.friend_link,name="friend_link"),
    url(r'^quanlification',zhengzihui_app.views.quanlification,name="quanlification"),
    #人工申诉
    url(r'^artificial_apeal',zhengzihui_app.views.artificial_apeal,name="artificial_apeal"),
    #联系我们
    url(r'^contact_us',zhengzihui_app.views.contact_us,name="contact_us"),
    #商业合作
    url(r'^business_cooperation',zhengzihui_app.views.business_cooperation,name="business_cooperation"),
    #网站联盟
    url(r'^union_website',zhengzihui_app.views.union_website,name="union_website"),
    #帐号申述
    url(r'^representations',zhengzihui_app.views.representations,name="representations"),
    #政资汇简介
    url(r'^introduce',zhengzihui_app.views.introduce,name="introduce"),
    #可信网站
    url(r'^trustedwebsite',zhengzihui_app.views.trustedwebsite,name="trustedwebsite"),


     #登陆注册
    url(r'^login/$', zhengzihui_app.views.login,name='login'),
    url(r'^logout/$',zhengzihui_app.views.logout,name='logout'),
    url(r'^g_register/$', zhengzihui_app.views.g_register,name='g_register'),
    url(r'^regCompany/$', zhengzihui_app.views.regCompany,name='regCompany'),
    url(r'^register2/$', zhengzihui_app.views.register2,name='register2'),
    url(r'^register3/$', zhengzihui_app.views.register3,name='register3'),
    url(r'^password1/$', zhengzihui_app.views.password1,name='password1'),
    url(r'^password2/$', zhengzihui_app.views.password2,name='password2'),
    url(r'^password3/$', zhengzihui_app.views.password3,name='password3'),
    url(r'^password4/$', zhengzihui_app.views.password4,name='password4'),
    url(r'^merchant/$',zhengzihui_app.views.merchant,name='merchant'),
    url(r'^merchantout/$',zhengzihui_app.views.merchantout,name='merchantout'),
    url(r'^applyforjoin/$',zhengzihui_app.views.applyforjoin,name='applyforjoin'),
    url(r'^success/$',zhengzihui_app.views.success,name='success'),
    url(r'^jff/$',zhengzihui_app.views.custpicforshow,name='custpicforshow'),


    
    
    #短信验证页
    url(r'^register_sms/$', zhengzihui_app.views.register_sms, name='register_sms'),
#    企业画像
    url(r'^custom/$', zhengzihui_app.views.custom,name='custom'),
    url(r'savec/$', zhengzihui_app.views.savec,name='savec'),
    url(r'custmap/$', zhengzihui_app.views.cmap,name='cmap'),


    #app下载
    url(r'^download/$', zhengzihui_app.views.download,name='download'),
    #支付选择页面
	url(r'^selectpay/$', zhengzihui_app.views.selectpay,name='selectpay'),
	#邮箱验证页
	url(r'^register2/(?P<token>\w+.[-_\w]*\w+.[-_\w]*\w+)/$',zhengzihui_app.views.active_user,name='active_user'),




    #点评管理
    url(r'^bus_comment_manager/$', zhengzihui_app.views.bus_comment_manager,name='bus_comment_manager'),
    url(r'^service_provider_reply/$', zhengzihui_app.views.service_provider_reply,name='service_provider_reply'),
    #信息维护
    url(r'^info_main/$', zhengzihui_app.views.info_main,name='info_main'),
	#商家入住首页
	url(r'^busindex/$',zhengzihui_app.views.busindex,name='busindex'),
	url(r'^buspubservice/',zhengzihui_app.views.buspubservice,name='buspubservice'),
	url(r'^busmaservice/',zhengzihui_app.views.busmaservice,name='busmaservice'),

	url(r'^merge_service_details/',zhengzihui_app.views.merge_service_details,name='merge_service_details'),
    #YZ
    url(r'^bus_order_manage/',zhengzihui_app.views.bus_order_manage,name="bus_order_manage"),
    url(r'^bus_counter_manage/',zhengzihui_app.views.bus_counter_manage,name="bus_counter_manage"),
    url(r'^change_paper_send_state/',zhengzihui_app.views.change_paper_send_state,name="change_paper_send_state"),
    url(r'^change_has_pay_state/',zhengzihui_app.views.change_has_pay_state,name="change_has_pay_state"),
    url(r'^sort_has_pay/',zhengzihui_app.views.sort_has_pay,name="sort_has_pay"),
    url(r'^sort_order_manage/',zhengzihui_app.views.sort_order_manage,name="sort_order_manage"),
    url(r'^busindex_sub/$',zhengzihui_app.views.busindex_sub,name='busindex_sub'),
	url(r'^b_work_index/$',zhengzihui_app.views.b_work_index,name='b_work_index'),
	url(r'^baforguests/$',zhengzihui_app.views.baforguests,name='baforguests'),
	url(r'^baforshopers/$',zhengzihui_app.views.baforshopers,name='baforshopers'),
	url(r'^bw_badetail/$',zhengzihui_app.views.bw_badetail,name='bw_badetail'),
	url(r'^bw_badetailfs/$',zhengzihui_app.views.bw_badetailfs,name='bw_badetailfs'),
    url(r'^baformerchantsupervisor/$',zhengzihui_app.views.ba_for_merchant_supervisor,name='ba_for_merchant_supervisor'), #后台管理/商家管理
	url(r'^bw_merchantsupervisor_detail/$',zhengzihui_app.views.bw_merchantsupervisor_detail,name='bw_merchantsupervisor_detail'),
    url(r'^b_work_comment_manager/$',zhengzihui_app.views.b_work_comment_manager,name='b_work_comment_manager'),
    url(r'^bpm_details/$',zhengzihui_app.views.bpm_details,name='bpm_details'),
    url(r'^bus_project_management/$',zhengzihui_app.views.bus_project_management,name='bus_project_management'),
    url(r'^balfororders/$',zhengzihui_app.views.balfororders,name='balfororders'),##houtaidingdanguanli
    url(r'^sort_order_time/',zhengzihui_app.views.sort_order_time,name="sort_order_time"),
    url(r'^bw_order_manage_detail/',zhengzihui_app.views.bw_order_manage_detail,name="bw_order_manage_detail"),#houtai管理查看详情 LQX 
    #配套商家
    url(r'^supporting_orders/',zhengzihui_app.views.supporting_orders,name="supporting_orders"),
    url(r'^sort_order/',zhengzihui_app.views.sort_order,name="sort_order"),
    url(r'^change_paper_send_state2/',zhengzihui_app.views.change_paper_send_state2,name="change_paper_send_state2"),
    url(r'^supporting_guests/',zhengzihui_app.views.supporting_guests,name="supporting_guests"),
    #融资商家
    url(r'^financing_orders/',zhengzihui_app.views.financing_orders,name="financing_orders"),


    # 信息共享-xy
    url(r'^shareinformation', zhengzihui_app.views.shareinformation, name="shareinformation"),
    # 发布人信息发布-xy
    url(r'^Publish', zhengzihui_app.views.Publish, name="Publish"),
    url(r'^change', zhengzihui_app.views.change, name="change"),

    #客服人员管理

zhengzihui/fr_app/models.py
#-*- coding:utf-8 -*-

from django.db import models

# Create your models here.

REQUIRE_TYPE = (
    (u'项目申报',u'项目申报'),
    (u'吸引投资',u'吸引投资'),
    (u'争取贷款',u'争取贷款'),
    (u'工商代理',u'工商代理'),
    (u'资质代办',u'资质代办'),
    (u'知识产权',u'知识产权'),
    (u'财务服务',u'财务服务'),
    ('N1','N1'),
)

class FRequireInfo(models.Model):
    info_id = models.AutoField("Information Id", primary_key=True)
    mobile_num = models.CharField("Mobile Number", max_length=30,null=False)
    require_type = models.CharField("Require type", max_length=30,choices=REQUIRE_TYPE,null=False)
    require_describe = models.CharField("Require description", max_length=255)
    news_time = models.DateTimeField("Release Data",auto_now=True)

    def __unicode__(self):
        return self.mobile_num+','+self.require_type


####supporting center part#####################################################
# designed by zp
class sc_item(models.Model):
    """这是配套服务中所提供商品的表单。
    图片存放在tb_album,tb_pic中，查找关系为 this.item_id <- tb_album.affiliation_id <- tb_pic.album_id .
    """
    item_id = models.AutoField('项目ID', primary_key=True)
    # 项目类型可选值为： '工商代理','资质代办','知识产权','财务服务'，'其他'
    item_type = models.CharField('项目类型',max_length=20,null=False,blank=False)
    price = models.CharField('价格',max_length=40,null=False)
    start_time = models.DateTimeField('项目发布时间',null=False)
    end_time = models.DateTimeField('项目截止时间',null=False)
    supplier = models.CharField('项目提供商',null=False,max_length=50)
    item_name = models.CharField('项目名称',max_length=100,null=False)
    item_details = models.TextField('项目内容',null=False)


# 这部分主要是摘抄自“服务列表页面”所使用的model
# 下面这部分表是为配套服务设置，由于表没有设计好


class sc_item_click(models.Model):
    item = models.ForeignKey(sc_item,verbose_name="项目id",null=False)
    
    itcl_id = models.IntegerField("项目分类id",null = False,default=0)
    click_counter = models.IntegerField("点击率",null = False,default=0)
    class Meta:
        verbose_name = '项目点击表'
        verbose_name_plural = '项目点击表'
    def __str__(self):
        return '项目id  '+str(self.item.item_id)+'  '+'关于                       '+str(self.item.item_name)+'                       的点击表'

"""
class sc_item_pa(models.Model):
    ipa_id = models.IntegerField('ID', primary_key=True,null=False)
    ipa_name = models.CharField('机构名称',max_length=100,null=False)
    ipa_parent_id = models.IntegerField('所属上级机构的id',null=False)
    ipa_sort = models.IntegerField('排序',null=False)
    area_id = models.IntegerField('机构对应地区的id',null=False)
    ipa_address = models.CharField('发布机构地址',max_length=1000,null=False,default='默认地址')#为了导航到该机构添加
    class Meta:
        verbose_name = '项目发布机构表'
        verbose_name_plural = '项目发布机构表'
    def __str__(self):   #python 2
        return self.ipa_name
"""

class sc_album(models.Model):
    album_id = models.IntegerField('ID', primary_key=True,null=False)
    album_name = models.CharField('相册名称',max_length=40,null=False)

    ITEM = 0
    GOODS = 1
    NEWS = 2
    NOTICE =3
    OTHER = 4
    ALBUM_TYPE = (
    (ITEM,'项目'),
    (GOODS,'商品'),
    (NEWS,'新闻'),
    (NOTICE,'公告'),
    (OTHER,'其他'),
    
    )
    album_type = models.IntegerField('相册类型',choices=ALBUM_TYPE,default=ITEM,null=False,blank=False)

    affiliation_id = models.IntegerField('相册的归属id',null=False)
    nacl_des = models.CharField('相册描述',max_length=100,null=False)
    nacl_sort = models.IntegerField('排序',null=False)
    upload_time = models.DateTimeField('相册建立时间',auto_now = True,null = False)

    NOTDEFAULT = 0
    ISDEFAULT = 1
   
    IS_DEFAULT = (
    (ISDEFAULT,'默认'),
    (NOTDEFAULT,'非默认'),
    
    )

    is_default = models.IntegerField('是否为默认相册',choices=IS_DEFAULT,default=ISDEFAULT,null=False,blank=False)
    class Meta:
        verbose_name = '相册表'
        verbose_name_plural = '相册表'
    def __str__(self):   #python 2
        return self.album_name



class sc_pic(models.Model):
    pic_id = models.IntegerField('ID', primary_key=True,null=False)
    pic_name = models.CharField('图片名称',max_length=40,null=False)
    pic_tag = models.CharField('图片标签',max_length=40,null=False)
    album_id = models.IntegerField('相册id',null=False)
    pic_object = models.ImageField('图片文件',upload_to='img_for_items/%Y/%m/%d',null = False,default="img_for_items/none/no_img.jpg")   
    pic_size = models.IntegerField('项目ID',null=False,default=0)
    upload_time = models.DateTimeField('图片上传时间',auto_now = True,null = False)
    class Meta:
        verbose_name = '图片表'
        verbose_name_plural = '图片表'
    def __str__(self):   #python 2
        return self.pic_name



class sc_article(models.Model):
    article_id = models.IntegerField('ID', primary_key=True,null=False)
    article_code = models.IntegerField('文章编码',null=False)
    article_name = models.CharField('文章名称',max_length=100,null=False)
    author = models.CharField('文章作者',max_length=100,null=False)
    author_email = models.CharField('作者邮箱',max_length=100,null=False)

    ITEM = 0
    GOODS = 1
    NEWS = 2
    NOTICE =3
    OTHER = 4
    ARTICLE_TYPE = (
    (ITEM,'项目'),
    (GOODS,'商品'),
    (NEWS,'新闻'),
    (NOTICE,'公告'),
    (OTHER,'其他'),
    
    )
    
    article_type = models.IntegerField('文章所属类型',choices=ARTICLE_TYPE,default=ITEM,null=False,blank=False)
    affiliation_id = models.IntegerField('文章的归属id',null=False)
    article_content = models.TextField('文章内容',null=False)
    article_keywords = models.TextField('文章关键字',null=False)
    article_des = models.CharField('文章描述',max_length=100,null=False)
    article_sort = models.IntegerField('排序',null=False)
    upload_time = models.DateTimeField('文章上传时间',auto_now =True,null = False)

    NOTDEFAULT = 0
    ISDEFAULT = 1
   
    IS_DEFAULT = (
    (ISDEFAULT,'默认'),
    (NOTDEFAULT,'非默认'),
    
    )
    is_default = models.IntegerField('是否为默认文章',choices=IS_DEFAULT,default=ISDEFAULT,null=False,blank=False)
    article_click = models.IntegerField('文章点击数',null=False)
    class Meta:
        verbose_name = '文章表'
        verbose_name_plural = '文章表'
    def __str__(self):   #python 2
        return self.article_name

zhengzihui/fr_app/forms.py
#-*- coding:utf-8 -*-

from django.forms import ModelForm,TextInput
from .models import FRequireInfo

class FRequireInfoForm(ModelForm):
    class Meta:
        model = FRequireInfo
        fields = '__all__'
        widgets = {
            'mobile_num': TextInput(attrs={'placeholder':'手机号码'}),
        }

zhengzihui/fr_app/templates/error.html
<div>
    sorry, I met a error here.
</div>

zhengzihui/fr_app/templates/frame.html
{% extends 'my_base.html' %}

{% block title %}免费发布需求{% endblock %}

{% block content %}
<style type="text/css">
.pub-free-tip {
	background: #f90;
	font-size: 14px;
	line-height: 35px;
	color: #fff;
	padding: 0 25px;
	font-weight: bold;
	border-top-left-radius: 5px;
	border-top-right-radius: 5px;
}
</style>

<div class='free_require_frame'>
    <div id='' style=''>
        <form id='' action="/free_require/require_finish/" method="post" class='form-horizontal' >
            <div class="pub-free-tip">官方提供线上担保交易，保障您的资金安全，且不会收取您任何佣金。 80%的欺诈、资金盗取均由线下交易导致，请勿线下交易。</div>
            <div style="background:#eee;padding: 16px 25px;">
            <fieldset style=''>
                <legend>输入你的手机号码并验证：</legend>
                <div class='form-group'>
                    <div class="col-sm-2">
                        {{ form.mobile_num }}
                        
                        <div style=''><font color="#FF0000">{{ err_msg.mobile_num }}</font></div>
                    </div>
                    <div class='col-sm-9'></div>
                </div>
                <div class='form-group'>
                    <div class='col-sm-2'>
                        <input type='text' name='vcode' id='vcode' placeholder="验证码" />
                        <div style=''><font color="#FF0000">{{err_msg.vcode}}</font></div>
                    </div>
                    <div class='col-sm-2'>
                        <input type="button" id="Verification" value="获取验证码" />
                    </div>
                    <div class='col-sm-8'></div>
                </div>
                <div class='form-group'>
                    <div class='col-sm-1'></div>
                    <div class='col-sm-1'>
                        <!-- input type="button" id="next" value="Next" style='display:none' /-->
                    </div>
                    <div class='col-sm-10'></div>
                </div>
            </fieldset>
            <fieldset style='display:block'>
                <legend>选择输入需求类型，方便我们分类：</legend>
                <div class='form-group'>
                    <div class='col-sm-2'>
                        {{ form.require_type }}
                    </div>
                    <div class='col-sm-10'></div>
                </div>
                <div class='form-group'>
                    <div class='col-sm-1'></div>
                    <div class='col-sm-1'>
                        <!--input type="button" id="next" value="Next" /-->
                    </div>
                </div>
            </fieldset>
            <fieldset style='display:block'>
                <legend>说说你的具体要求：</legend>
                <div class='form-group'>
                    <div class='col-sm-12'>
                        <textarea name='require_describe' rows="15" cols=100% value="{{ require_type }}"  placeholder='描述你自己的详细需求'></textarea>
                    </div>
                </div>
                <div style=''><font color="#FF0000">{{err_msg.other}}</font></div>
                <div class='form-group'>
                    <div class='col-sm-1'>
                        <input type="submit" id="submit" value="提交表单" style='width:200%'/>
                    </div>
                    <div class='col-sm-1'>
                        
                    </div>
                    <div class='col-sm-1'>
                        <input type="reset" id="reset" value="重置表单" style='width:200%'/>
                    </div>
                    <div class='col-sm-9'></div>
                </div>
            </fieldset>
            </div>
        </form>
    </div>
</div>
<script type="text/javascript">
    $('input#Verification').click(function(){
        var reg = /^(((13[0-9]{1})|(15[0-9]{1})|(18[0-9]{1}))+\d{8})$/; 
        if(!reg.test($("input#id_mobile_num").val())) 
        { 
            alert('请输入有效的手机号码！'); 
            return false; 
        }

        //ajax to 
        var mobile_num = $('input#id_mobile_num').val();
        var fd = new FormData();
        fd.append("mobile_num",mobile_num);

        $.ajax({
            url: '/free_require/verification/',
            data: fd,
            processData: false,
            contentType: false,
            type: 'POST',
            success: function(data){

                if (data=='success') {
                    $('input#id_mobile_num').attr('readonly','true');
                    $('input#Verification').hide();
                    //$('input#next').show();
                }
            }
        });

    });

</script>
<script type="text/javascript">
    var reg = /^(((13[0-9]{1})|(15[0-9]{1})|(18[0-9]{1}))+\d{8})$/; 
    if(!reg.test($("input#id_mobile_num").val())) 
    { 
        alert('请输入有效的手机号码！'); 
        return false; 
    } 
</script>
{% endblock %}

zhengzihui/fr_app/templates/moble_verification.html
<div class='verification'>
    <div>here is mobile verification</div>
    <div>error: {{err_msg}}</div>
    <div>
        <input id='mobile_num' type="text" name="mobile_num" />
        <button id="next_step" type="button">Next</button></div>
</div>

<script type="text/javascript">

    var fd = new FormData();
    fd.append("mobile_num",'123456');

    $('button#next_step').click(function(){
        $.ajax({
            url: '/free_require/verification/',
            data: fd,
            processData: false,
            contentType: false,
            type: 'POST',
            success: function(data){
                $('div#fr_body').children().remove();
                $('#fr_body').append(data);
            }
        });

    });

</script>

zhengzihui/fr_app/templates/require_description.html
<div class='require_description' >
    <div >here is require description</div>
    <div>error: {{err_msg}}</div>
    <button id="finish_step" type="button">Finish</button>
</div>

<script type="text/javascript">

    var fd = new FormData();
    fd.append("require_description",'xxxx');

    $('button#finish_step').click(function(){
        $.ajax({
            url: '/free_require/require_description/',
            data: fd,
            processData: false,
            contentType: false,
            type: 'POST',
            success: function(data){

                $('div#fr_body').children().remove();
                $('#fr_body').append(data);
            }
        });

    });

</script>

zhengzihui/fr_app/templates/require_finish.html
<div class='require_finish' >
    <div >succeed release require information.</div>
</div>

zhengzihui/fr_app/templates/require_type.html
<div class='require_type'>
    <div >here is require type</div>
    <div>error: {{err_msg}}</div>
    <button id="next_step" type="button">Next</button>
</div>

<script type="text/javascript">

    var fd = new FormData();
    fd.append("require_type",'N1');

    $('button#next_step').click(function(){
        $.ajax({
            url: '/free_require/require_type/',
            data: fd,
            processData: false,
            contentType: false,
            type: 'POST',
            success: function(data){

                $('div#fr_body').children().remove();
                $('#fr_body').append(data);
            }
        });

    });

</script>